name: file_picker
description: A plugin that allows you to filter and pick absolute paths for diferent file extensions.
version: 1.3.0
author: Miguel Ruivo <miguelpruivo@outlook.com>
homepage: https://github.com/miguelpruivo/plugins_flutter_file_picker


dependencies:
  flutter:
    sdk: flutter
    
environment:
  sdk: ">=2.0.0 <3.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.mr.flutter.plugin.filepicker
    pluginClass: FilePickerPlugin

